version: "3"
services:

  balancer:
    image: balancer
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - client
      - server
    networks:
      - internal

  client:
    image: client
    volumes:
      - ./client:/app/
    networks:
      - internal

  server:
    image: server
    environment:
      - DB_URI=mongodb://db/donnyslist
    volumes:
      - ./server:/app
    depends_on:
      - db
    networks:
      - internal

  db:
    image: db
    ports:
      - "27017:27017"
    volumes:
      - /var/lib/mongodb:/data/db
    networks:
      - internal

networks:
  internal:
