version: "3"
services:

  balancer:
    image: balancer
    ports:
      - "0.0.0.0:81:80"
    depends_on:
      - client
      - server
    networks:
      - internal

  client:
    image: client
    volumes:
      - ./client:/etc/nginx/html/
    networks:
      - internal

  server:
    image: server
    environment:
      - DB_URI=mongodb://db/donnyslist
    volumes:
      - ./server:/app
    depends_on:
      - db
    networks:
      - internal

  db:
    image: db
    ports:
      - "27017:27017"
    volumes:
      - ./data/db:/data/db
    networks:
      - internal

networks:
  internal:
